---
with-expecter: true
filename: "mock_{{.InterfaceName | snakecase}}.go"
packages:
  github.com/ncotds/nco-qoordinator/pkg/querycoordinator:
    config:
      dir: "{{.InterfaceDir}}/mocks"
    interfaces:
      Client:
  github.com/ncotds/nco-qoordinator/pkg/dbconnector:
    config:
      dir: "{{.InterfaceDir}}/mocks"
    interfaces:
      ExecutorCloser:
      DBConnector: