repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks: 
      - id: go-fmt
      - id: go-imports
      - id: go-mod-tidy
      - id: go-cyclo
        args: [-over=15]
      - id: golangci-lint
