---
name: PR check code

on:
  pull_request:
    branches:
      - '*'

env:
  GO_VERSION: '1.22'
  GOLANGCI_LINT_VERSION: v1.57.0
  GOTESTSUM_VERSION: v1.11.0

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install golangci-lint ${{ env.GOLANGCI_LINT_VERSION }}
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_LINT_VERSION}

      - name: Lint
        run: make lint

  test-unit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install gotestsum ${{ env.GOTESTSUM_VERSION }}
        run: go install gotest.tools/gotestsum@${GOTESTSUM_VERSION}

      - name: Tests
        run: make test-unit

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-unit
          path: coverage.xml

  test-publish-results:
    runs-on: ubuntu-latest
    needs: test-unit
    if: ${{ always() }}

    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    steps:
      - name: Download reports
        uses: actions/download-artifact@v4
        with:
          name: coverage-unit

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            coverage*.xml