---
name: Deploy to test environment

on:
  push:
    branches:
      - test

env:
  GO_VERSION: '1.22'
  GOLANGCI_LINT_VERSION: v1.57.0
  GOTESTSUM_VERSION: v1.11.0

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install golangci-lint ${{ env.GOLANGCI_LINT_VERSION }}
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_LINT_VERSION}

      - name: Lint
        run: make lint

  test-unit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install gotestsum ${{ env.GOTESTSUM_VERSION }}
        run: go install gotest.tools/gotestsum@${GOTESTSUM_VERSION}

      - name: Tests
        run: make test-unit

  build:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test-unit

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: echo TBD build here

  deploy-test:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to test
        run: echo TBD build here
